# config file for meteo-france

datagouvfr:
  # data.gouv.fr base URL
  base_url: https://demo.data.gouv.fr
  # oauth settings
  oauth_client_id:
  # pkce client secret, explicitely public
  oauth_client_secret:

universe:
  # "universe" topic id
  topic_id: 650da7e9ac89b5a2ac75a11a # meteo-test
  # universe name, used as bouquets tag
  name: meteo-france

# UI customizations
website:
  title: 'meteo.data.gouv.fr'
  rf_title: 'RÉPUBLIQUE<br>
    FRANÇAISE'
  # leave empty if not pertinent
  logo_operator: 'https://static.data.gouv.fr/avatars/81/6374003e904fad9ddac7436315fd15-100.png'
  homepage_title: 'La météo et le climat en Open Data'
  homepage_subtitle: 'meteo.data.gouv.fr centralise et structure les données publiques relatives à la météo et au climat. Vous y trouverez des données téléchargeables et utilisables de manière libre et gratuite.'
  search_bar:
    display: true
    placeholder: 'Rechercher un jeu de données'
  secondary_search:
    display: true
    name: 'Recherche guidée'
    link: '/form'
  menu_items:
    - name: 'Accueil'
      id: 'home'
      linkPage: '/'
      type: 'component'
      display_menu: false
    - name: 'Données'
      id: 'datasets'
      linkPage: '/datasets'
      type: 'component'
      display_menu: true
    - name: 'Recherche guidée'
      id: 'FormMF'
      linkPage: '/form'
      type: 'custom'
      path: '../custom/meteo/views/FormMF.vue'
      display_menu: true
    - name: 'A propos'
      id: 'about'
      linkPage: '/about'
      type: 'page'
      url: 'https://gist.githubusercontent.com/geoffreyaldebert/4e95103bff159c578db3941619fb9cfd/raw/36d7b3b0784d07b36208b6e9f353454e6dd639be/gistfile1.txt'
      display_menu: true
  # img should be square
  home_buttons:
    - title: 'En savoir plus sur la démarche'
      link: '/about'
      img: 'https://static.data.gouv.fr/avatars/44/3f1d6b9eac45b2bca7ae9b2a80d812-100.jpg'
    - title: 'Utiliser les API Météo-France'
      link: 'https://portail-api.meteofrance.fr/devportal/apis'
      img: 'https://static.data.gouv.fr/avatars/40/05f4e0291e4ad49a9321071c195cce-100.jpg'
    - title: 'Voir les jeux de données récents'
      link: '/datasets'
      img: 'https://transport.data.gouv.fr/images/icons/recently-added-datasets-cbc8b7a7d744618cfe4d97a32e5570ac.png?vsn=d'
  show_topic_charts: true
  list_highlighted_topics:
    - id: '653a6eee7a6aa39deaec2de9'
      name: 'Données climatologiques de base'
    - id: '653a6f43e96894d0275c994c'
      name: 'Données climatologique de référence pour le changement climatique'
  oauth_option: false
  # display settings
  pagination_sizes:
    organizations_list: 9
    topics_list: 100
  home_banner_colors:
    - '#F7EED4'
    - '#ECEEE6'
    - '#E2EEF8'

# list of organisations' ids that should be handled by the portal
# to find an id go to https://www.data.gouv.fr/fr/organizations/ministere-de-la-transition-ecologique/
# then Informations > ID at the bottom of the page
organizations:

departements:
  - code: '01'
    name: Ain
  - code: '02'
    name: Aisne
  - code: '03'
    name: Allier
  - code: '04'
    name: Alpes-de-Haute-Provence
  - code: '05'
    name: Hautes-Alpes
  - code: '06'
    name: Alpes-Maritimes
  - code: '07'
    name: Ardèche
  - code: '08'
    name: Ardennes
  - code: '09'
    name: Ariège
  - code: '10'
    name: Aube
  - code: '11'
    name: Aude
  - code: '12'
    name: Aveyron
  - code: '13'
    name: Bouches-du-Rhône
  - code: '14'
    name: Calvados
  - code: '15'
    name: Cantal
  - code: '16'
    name: Charente
  - code: '17'
    name: Charente-Maritime
  - code: '18'
    name: Cher
  - code: '19'
    name: Corrèze
  - code: '21'
    name: Côte-d'Or
  - code: '22'
    name: Côtes-d'Armor
  - code: '23'
    name: Creuse
  - code: '24'
    name: Dordogne
  - code: '25'
    name: Doubs
  - code: '26'
    name: Drôme
  - code: '27'
    name: Eure
  - code: '28'
    name: Eure-et-Loir
  - code: '29'
    name: Finistère
  - code: 2A
    name: Corse-du-Sud
  - code: 2B
    name: Haute-Corse
  - code: '30'
    name: Gard
  - code: '31'
    name: Haute-Garonne
  - code: '32'
    name: Gers
  - code: '33'
    name: Gironde
  - code: '34'
    name: Hérault
  - code: '35'
    name: Ille-et-Vilaine
  - code: '36'
    name: Indre
  - code: '37'
    name: Indre-et-Loire
  - code: '38'
    name: Isère
  - code: '39'
    name: Jura
  - code: '40'
    name: Landes
  - code: '41'
    name: Loir-et-Cher
  - code: '42'
    name: Loire
  - code: '43'
    name: Haute-Loire
  - code: '44'
    name: Loire-Atlantique
  - code: '45'
    name: Loiret
  - code: '46'
    name: Lot
  - code: '47'
    name: Lot-et-Garonne
  - code: '48'
    name: Lozère
  - code: '49'
    name: Maine-et-Loire
  - code: '50'
    name: Manche
  - code: '51'
    name: Marne
  - code: '52'
    name: Haute-Marne
  - code: '53'
    name: Mayenne
  - code: '54'
    name: Meurthe-et-Moselle
  - code: '55'
    name: Meuse
  - code: '56'
    name: Morbihan
  - code: '57'
    name: Moselle
  - code: '58'
    name: Nièvre
  - code: '59'
    name: Nord
  - code: '60'
    name: Oise
  - code: '61'
    name: Orne
  - code: '62'
    name: Pas-de-Calais
  - code: '63'
    name: Puy-de-Dôme
  - code: '64'
    name: Pyrénées-Atlantiques
  - code: '65'
    name: Hautes-Pyrénées
  - code: '66'
    name: Pyrénées-Orientales
  - code: '67'
    name: Bas-Rhin
  - code: '68'
    name: Haut-Rhin
  - code: '69'
    name: Rhône
  - code: '70'
    name: Haute-Saône
  - code: '71'
    name: Saône-et-Loire
  - code: '72'
    name: Sarthe
  - code: '73'
    name: Savoie
  - code: '74'
    name: Haute-Savoie
  - code: '75'
    name: Paris
  - code: '76'
    name: Seine-Maritime
  - code: '77'
    name: Seine-et-Marne
  - code: '78'
    name: Yvelines
  - code: '79'
    name: Deux-Sèvres
  - code: '80'
    name: Somme
  - code: '81'
    name: Tarn
  - code: '82'
    name: Tarn-et-Garonne
  - code: '83'
    name: Var
  - code: '84'
    name: Vaucluse
  - code: '85'
    name: Vendée
  - code: '86'
    name: Vienne
  - code: '87'
    name: Haute-Vienne
  - code: '88'
    name: Vosges
  - code: '89'
    name: Yonne
  - code: '90'
    name: Territoire de Belfort
  - code: '91'
    name: Essonne
  - code: '92'
    name: Hauts-de-Seine
  - code: '93'
    name: Seine-Saint-Denis
  - code: '94'
    name: Val-de-Marne
  - code: '95'
    name: Val-d'Oise
  - code: '971'
    name: Guadeloupe
  - code: '972'
    name: Martinique
  - code: '973'
    name: Guyane
  - code: '974'
    name: La Réunion
  - code: '976'
    name: Mayotte
  - code: '975'
    name: Saint-Pierre-et-Miquelon
  - code: '977'
    name: Saint-Barthélemy
  - code: '978'
    name: Saint-Martin
  - code: '984'
    name: Terres australes et antarctiques françaises
  - code: '986'
    name: Wallis et Futuna
  - code: '987'
    name: Polynésie française
  - code: '988'
    name: Nouvelle-Calédonie
  - code: '989'
    name: Île de Clipperton
